/**
 * A map from Mixamo rig name to VRM Humanoid bone name
 */
export const VRMRigMap = {
	J_Bip_C_Hips: 'hips',
	J_Bip_C_Spine: 'spine',
	J_Bip_C_Chest: 'chest',
	J_Bip_C_UpperChest: 'upperChest',
	J_Bip_C_Neck: 'neck',
	J_Bip_C_Head: 'head',
	J_Bip_L_Shoulder: 'leftShoulder',
	J_Bip_L_UpperArm: 'leftUpperArm',
	J_Bip_L_LowerArm: 'leftLowerArm',
	J_Bip_L_Hand: 'leftHand',
	J_Bip_L_Thumb1: 'leftThumbMetacarpal',
	J_Bip_L_Thumb2: 'leftThumbProximal',
	J_Bip_L_Thumb3: 'leftThumbDistal',
	J_Bip_L_Index1: 'leftIndexProximal',
	J_Bip_L_Index2: 'leftIndexIntermediate',
	J_Bip_L_Index3: 'leftIndexDistal',
	J_Bip_L_Middle1: 'leftMiddleProximal',
	J_Bip_L_Middle2: 'leftMiddleIntermediate',
	J_Bip_L_Middle3: 'leftMiddleDistal',
	J_Bip_L_Ring1: 'leftRingProximal',
	J_Bip_L_Ring2: 'leftRingIntermediate',
	J_Bip_L_Ring3: 'leftRingDistal',
	J_Bip_L_Little1: 'leftLittleProximal',
	J_Bip_L_Little2: 'leftLittleIntermediate',
	J_Bip_L_Little3: 'leftLittleDistal',
	J_Bip_R_Shoulder: 'rightShoulder',
	J_Bip_R_UpperArm: 'rightUpperArm',
	J_Bip_R_LowerArm: 'rightLowerArm',
	J_Bip_R_Hand: 'rightHand',
	J_Bip_R_Little1: 'rightLittleProximal',
	J_Bip_R_Little2: 'rightLittleIntermediate',
	J_Bip_R_Little3: 'rightLittleDistal',
	J_Bip_R_Ring1: 'rightRingProximal',
	J_Bip_R_Ring2: 'rightRingIntermediate',
	J_Bip_R_Ring3: 'rightRingDistal',
	J_Bip_R_Middle1: 'rightMiddleProximal',
	J_Bip_R_Middle2: 'rightMiddleIntermediate',
	J_Bip_R_Middle3: 'rightMiddleDistal',
	J_Bip_R_Index1: 'rightIndexProximal',
	J_Bip_R_Index2: 'rightIndexIntermediate',
	J_Bip_R_Index3: 'rightIndexDistal',
	J_Bip_R_Thumb1: 'rightThumbMetacarpal',
	J_Bip_R_Thumb2: 'rightThumbProximal',
	J_Bip_R_Thumb3: 'rightThumbDistal',
	J_Bip_L_UpperLeg: 'leftUpperLeg',
	J_Bip_L_LowerLeg: 'leftLowerLeg',
	J_Bip_L_Foot: 'leftFoot',
	J_Bip_L_ToeBase: 'leftToes',
	J_Bip_R_UpperLeg: 'rightUpperLeg',
	J_Bip_R_LowerLeg: 'rightLowerLeg',
	J_Bip_R_Foot: 'rightFoot',
	J_Bip_R_ToeBase: 'rightToes',
};
